[package]
name = "flack"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "flack-serve"
path = "src/main.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6.7"
anyhow = "1.0"
log = "0.4.28"
env_logger = "0.11.8"
tokio = { version = "1", features = ["full"] }
nix-expr = { path = "../nix-expr" }
nix-fetchers = { path = "../nix-fetchers" }
nix-flake = { path = "../nix-flake" }
nix-store = { path = "../nix-store" }
nix-util = { path = "../nix-util" }

[dependencies.uuid]
version = "1.18.1"
features = [
    "v7"
]
