[workspace]
members = [
    "flack-serve"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = [
  "Morgan Jones <me@numin.it>"
]
edition = "2024"
license = "LGPL"
homepage = "https://github.com/numinit/flack"
repository = "https://github.com/numinit/flack"
